### ISSUE TITLE
Apparently it’s not possible to get current average pop-up details

### ISSUE THREAD

**Issue by LucasAlfare** [Kubiverse/Cube-Zone#6]
**Bug**
After creating a room and starting performing 5 solves (I was solo), couldn't see a pop-up of the current average 5. Then basically the panel still loading without any results, as shown in the screenshot bellow.

**To Reproduce**
I just logged in with WCA credentials and started a public Square-1 room, without passwords.

**Expected behavior**
Should average details appear in pop-up panel?

**Screenshots**
![image](https://user-images.githubusercontent.com/16053500/82152186-f9365e80-9835-11ea-86d3-1b354321bc70.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 81.0.4044.138 64-bits

**Comment by LucasAlfare** [comment]
Apparently not working yet. At right you can see the console errors.

![image](https://user-images.githubusercontent.com/16053500/82397373-b2f42180-9a26-11ea-87bf-c3a16308979f.png)

**Comment by big213** [comment]
Ah yeah, it was fixed but we haven't deployed the latest release to the production website yet. We are trying to stick to a release schedule (a new release every weekend), but since this is kind of a breaking issue, I think we can deploy something right away.

**Comment by big213** [comment]
Just deployed a new minor release 1.0.7, you can read the notes here: https://github.com/Kubiverse/Cube-Zone/releases/tag/1.0.7

Let me know if it is still not working
